"""initial_schema

Revision ID: 2acf024f2522
Revises: 
Create Date: 2026-03-26 19:24:15.883609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '2acf024f2522'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_id', app.models.types.GUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', app.models.types.JSONType(), nullable=True),
    sa.Column('phi_accessed', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('settings', app.models.types.JSONType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('payers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payer_id_code', sa.String(length=50), nullable=False),
    sa.Column('payer_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('electronic_payer_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payers_payer_id_code'), 'payers', ['payer_id_code'], unique=True)
    op.create_table('phi_access_log',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', app.models.types.GUID(), nullable=False),
    sa.Column('patient_id', app.models.types.GUID(), nullable=True),
    sa.Column('access_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('phi_fields_accessed', app.models.types.JSONType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phi_access_log_timestamp'), 'phi_access_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_phi_access_log_user_id'), 'phi_access_log', ['user_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', 'timed_out', name='workflow_status_enum'), nullable=False),
    sa.Column('task_queue', sa.String(length=255), nullable=True),
    sa.Column('input_data', app.models.types.JSONType(), nullable=True),
    sa.Column('output_data', app.models.types.JSONType(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    op.create_index(op.f('ix_workflow_executions_agent_type'), 'workflow_executions', ['agent_type'], unique=False)
    op.create_table('clearinghouse_configs',
    sa.Column('organization_id', app.models.types.GUID(), nullable=False),
    sa.Column('clearinghouse_name', sa.String(length=100), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=False),
    sa.Column('credentials', app.models.types.JSONType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supported_transactions', app.models.types.JSONType(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clearinghouse_configs_organization_id'), 'clearinghouse_configs', ['organization_id'], unique=False)
    op.create_table('patients',
    sa.Column('organization_id', app.models.types.GUID(), nullable=False),
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('external_ehr_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('insurance_member_id', sa.String(length=100), nullable=True),
    sa.Column('insurance_group_id', sa.String(length=100), nullable=True),
    sa.Column('payer_id', app.models.types.GUID(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=False)
    op.create_table('payer_rules',
    sa.Column('payer_id', app.models.types.GUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', app.models.types.JSONType(), nullable=False),
    sa.Column('actions', app.models.types.JSONType(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payer_rules_agent_type'), 'payer_rules', ['agent_type'], unique=False)
    op.create_index(op.f('ix_payer_rules_payer_id'), 'payer_rules', ['payer_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'reviewer', 'viewer', name='user_role'), nullable=False),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_subject_id', sa.String(length=255), nullable=True),
    sa.Column('organization_id', app.models.types.GUID(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_tasks',
    sa.Column('agent_type', sa.Enum('eligibility', 'scheduling', 'claims', 'prior_auth', 'credentialing', 'compliance', name='agent_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', 'review', name='task_status_enum'), nullable=False),
    sa.Column('organization_id', app.models.types.GUID(), nullable=True),
    sa.Column('patient_id', app.models.types.GUID(), nullable=True),
    sa.Column('input_data', app.models.types.JSONType(), nullable=True),
    sa.Column('output_data', app.models.types.JSONType(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('workflow_execution_id', app.models.types.GUID(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_agent_type'), 'agent_tasks', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('encounters',
    sa.Column('patient_id', app.models.types.GUID(), nullable=False),
    sa.Column('encounter_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('encounter_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_npi', sa.String(length=20), nullable=True),
    sa.Column('facility_npi', sa.String(length=20), nullable=True),
    sa.Column('diagnosis_codes', app.models.types.JSONType(), nullable=True),
    sa.Column('procedure_codes', app.models.types.JSONType(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('task_id', app.models.types.GUID(), nullable=False),
    sa.Column('patient_id', app.models.types.GUID(), nullable=False),
    sa.Column('encounter_id', app.models.types.GUID(), nullable=True),
    sa.Column('payer_id', app.models.types.GUID(), nullable=True),
    sa.Column('claim_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('claim_number', sa.String(length=100), nullable=True),
    sa.Column('total_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('patient_responsibility', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('diagnosis_codes', app.models.types.JSONType(), nullable=True),
    sa.Column('procedure_codes', app.models.types.JSONType(), nullable=True),
    sa.Column('submission_data', app.models.types.JSONType(), nullable=True),
    sa.Column('remittance_data', app.models.types.JSONType(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=False)
    op.create_index(op.f('ix_claims_task_id'), 'claims', ['task_id'], unique=False)
    op.create_table('compliance_reports',
    sa.Column('task_id', app.models.types.GUID(), nullable=False),
    sa.Column('organization_id', app.models.types.GUID(), nullable=False),
    sa.Column('measure_set', sa.String(length=50), nullable=False),
    sa.Column('reporting_period_start', sa.String(length=10), nullable=False),
    sa.Column('reporting_period_end', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('measure_scores', app.models.types.JSONType(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('gaps_identified', sa.Integer(), nullable=True),
    sa.Column('gap_details', app.models.types.JSONType(), nullable=True),
    sa.Column('recommendations', app.models.types.JSONType(), nullable=True),
    sa.Column('report_data', app.models.types.JSONType(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reports_task_id'), 'compliance_reports', ['task_id'], unique=False)
    op.create_table('credentialing_applications',
    sa.Column('task_id', app.models.types.GUID(), nullable=False),
    sa.Column('provider_npi', sa.String(length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('target_organization', sa.String(length=255), nullable=True),
    sa.Column('target_payer_id', app.models.types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('documents_checklist', app.models.types.JSONType(), nullable=True),
    sa.Column('missing_documents', app.models.types.JSONType(), nullable=True),
    sa.Column('licenses', app.models.types.JSONType(), nullable=True),
    sa.Column('sanctions_check', app.models.types.JSONType(), nullable=True),
    sa.Column('application_data', app.models.types.JSONType(), nullable=True),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentialing_applications_provider_npi'), 'credentialing_applications', ['provider_npi'], unique=False)
    op.create_index(op.f('ix_credentialing_applications_task_id'), 'credentialing_applications', ['task_id'], unique=False)
    op.create_table('eligibility_checks',
    sa.Column('task_id', app.models.types.GUID(), nullable=False),
    sa.Column('patient_id', app.models.types.GUID(), nullable=False),
    sa.Column('payer_id', app.models.types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('request_data', app.models.types.JSONType(), nullable=True),
    sa.Column('response_data', app.models.types.JSONType(), nullable=True),
    sa.Column('coverage_active', sa.Boolean(), nullable=True),
    sa.Column('coverage_details', app.models.types.JSONType(), nullable=True),
    sa.Column('transaction_id_270', sa.String(length=100), nullable=True),
    sa.Column('transaction_id_271', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_checks_task_id'), 'eligibility_checks', ['task_id'], unique=False)
    op.create_table('hitl_reviews',
    sa.Column('task_id', app.models.types.GUID(), nullable=False),
    sa.Column('reviewer_id', app.models.types.GUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'escalated', name='review_status_enum'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('agent_decision', app.models.types.JSONType(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hitl_reviews_task_id'), 'hitl_reviews', ['task_id'], unique=False)
    op.create_table('prior_auth_requests',
    sa.Column('task_id', app.models.types.GUID(), nullable=False),
    sa.Column('patient_id', app.models.types.GUID(), nullable=False),
    sa.Column('payer_id', app.models.types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('procedure_code', sa.String(length=20), nullable=False),
    sa.Column('diagnosis_codes', app.models.types.JSONType(), nullable=True),
    sa.Column('clinical_info', app.models.types.JSONType(), nullable=True),
    sa.Column('submission_channel', sa.String(length=50), nullable=True),
    sa.Column('auth_number', sa.String(length=100), nullable=True),
    sa.Column('determination', sa.String(length=30), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('request_data_278', app.models.types.JSONType(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prior_auth_requests_task_id'), 'prior_auth_requests', ['task_id'], unique=False)
    op.create_table('scheduling_requests',
    sa.Column('task_id', app.models.types.GUID(), nullable=False),
    sa.Column('patient_id', app.models.types.GUID(), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('parsed_intent', app.models.types.JSONType(), nullable=True),
    sa.Column('provider_npi', sa.String(length=20), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('preferred_date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('appointment_fhir_id', sa.String(length=255), nullable=True),
    sa.Column('appointment_details', app.models.types.JSONType(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_requests_task_id'), 'scheduling_requests', ['task_id'], unique=False)
    op.create_table('claim_denials',
    sa.Column('claim_id', app.models.types.GUID(), nullable=False),
    sa.Column('denial_code', sa.String(length=20), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=False),
    sa.Column('denial_category', sa.String(length=100), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('appeal_status', sa.String(length=30), nullable=True),
    sa.Column('appeal_details', app.models.types.JSONType(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_denials_claim_id'), 'claim_denials', ['claim_id'], unique=False)
    op.create_table('prior_auth_appeals',
    sa.Column('prior_auth_id', app.models.types.GUID(), nullable=False),
    sa.Column('appeal_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('appeal_letter', sa.Text(), nullable=True),
    sa.Column('clinical_evidence', app.models.types.JSONType(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('outcome_details', app.models.types.JSONType(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prior_auth_id'], ['prior_auth_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prior_auth_appeals_prior_auth_id'), 'prior_auth_appeals', ['prior_auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prior_auth_appeals_prior_auth_id'), table_name='prior_auth_appeals')
    op.drop_table('prior_auth_appeals')
    op.drop_index(op.f('ix_claim_denials_claim_id'), table_name='claim_denials')
    op.drop_table('claim_denials')
    op.drop_index(op.f('ix_scheduling_requests_task_id'), table_name='scheduling_requests')
    op.drop_table('scheduling_requests')
    op.drop_index(op.f('ix_prior_auth_requests_task_id'), table_name='prior_auth_requests')
    op.drop_table('prior_auth_requests')
    op.drop_index(op.f('ix_hitl_reviews_task_id'), table_name='hitl_reviews')
    op.drop_table('hitl_reviews')
    op.drop_index(op.f('ix_eligibility_checks_task_id'), table_name='eligibility_checks')
    op.drop_table('eligibility_checks')
    op.drop_index(op.f('ix_credentialing_applications_task_id'), table_name='credentialing_applications')
    op.drop_index(op.f('ix_credentialing_applications_provider_npi'), table_name='credentialing_applications')
    op.drop_table('credentialing_applications')
    op.drop_index(op.f('ix_compliance_reports_task_id'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_claims_task_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent_type'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payer_rules_payer_id'), table_name='payer_rules')
    op.drop_index(op.f('ix_payer_rules_agent_type'), table_name='payer_rules')
    op.drop_table('payer_rules')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_clearinghouse_configs_organization_id'), table_name='clearinghouse_configs')
    op.drop_table('clearinghouse_configs')
    op.drop_index(op.f('ix_workflow_executions_agent_type'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_phi_access_log_user_id'), table_name='phi_access_log')
    op.drop_index(op.f('ix_phi_access_log_timestamp'), table_name='phi_access_log')
    op.drop_table('phi_access_log')
    op.drop_index(op.f('ix_payers_payer_id_code'), table_name='payers')
    op.drop_table('payers')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')

    # Explicitly drop PostgreSQL enum types created in upgrade.
    # On non-PostgreSQL backends this is a no-op (bind.dialect.name check).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "review_status_enum",
            "task_status_enum",
            "agent_type_enum",
            "workflow_status_enum",
            "user_role",
        ):
            op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
